### ISSUE TITLE
Update to 1.10.2?

### ISSUE THREAD

**Issue by Malvagio87** [scarabcoder/Discord2MC#1]
Any chance you are going to update this to 1.10.2?

I am looking for something like this and just installed it on a 1.9 client to test it out.

I think it does what i want, but I was wondering about a few things.

Is it possible to choose one channel for it to focus on?  I am part of like 10 server and my screen is just spammed with text.

Is it possible to talk directly in game to the discord channel?
For instance by typing "~" before a message, it would send it to the default channel?

**Comment by scarabcoder** [comment]
Hi Malv,
I plan to update it, but I've been busy with other projects. I'll try updating most of my mods to 1.10.2, and add a mute option. I'll look into chatting with people on Discord, though capturing chat messages sent by players is a bit difficult.
